console.log("Hello!");

const movie = {
   Title: "The Batman",
   Year: "2022",
   Rated: "PG-13",
   Released: "04 Mar 2022",
   Runtime: "176 min",
   Genre: "Action, Crime, Drama",
   Director: "Matt Reeves",
   Writer: "Matt Reeves, Peter Craig, Bob Kane",
   Actors: "Robert Pattinson, Zoë Kravitz, Jeffrey Wright",
   Plot: "When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the city's hidden corruption and question his family's involvement.",
   Language: "English, Spanish, Latin, Italian",
   Country: "United States",
   Awards: "2 wins & 25 nominations",
   Poster:
      "https://m.media-amazon.com/images/M/MV5BMDdmMTBiNTYtMDIzNi00NGVlLWIzMDYtZTk3MTQ3NGQxZGEwXkEyXkFqcGdeQXVyMzMwOTU5MDk@._V1_SX300.jpg",
   Ratings: [
      { Source: "Internet Movie Database", Value: "7.9/10" },
      { Source: "Rotten Tomatoes", Value: "85%" },
      { Source: "Metacritic", Value: "72/100" },
   ],
   Metascore: "72",
   imdbRating: "7.9",
   imdbVotes: "570,429",
   imdbID: "tt1877830",
   Type: "movie",
   DVD: "19 Apr 2022",
   BoxOffice: "$369,345,583",
   Production: "N/A",
   Website: "N/A",
   Response: "True",
};
const series = {
   Title: "Game of Thrones",
   Year: "2011–2019",
   Rated: "TV-MA",
   Released: "17 Apr 2011",
   Runtime: "57 min",
   Genre: "Action, Adventure, Drama",
   Director: "N/A",
   Writer: "David Benioff, D.B. Weiss",
   Actors: "Emilia Clarke, Peter Dinklage, Kit Harington",
   Plot: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
   Language: "English",
   Country: "United States, United Kingdom",
   Awards: "Won 59 Primetime Emmys. 387 wins & 632 nominations total",
   Poster:
      "https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_SX300.jpg",
   Ratings: [{ Source: "Internet Movie Database", Value: "9.2/10" }],
   Metascore: "N/A",
   imdbRating: "9.2",
   imdbVotes: "2,025,740",
   imdbID: "tt0944947",
   Type: "series",
   totalSeasons: "8",
   Response: "True",
};

console.log(movie, series);
